name: Build Go executable and deploy over SSH (preset 2)
on:
  workflow_call:
    inputs:
      executableFilename:
        required: false
        type: string
        default: ${{ vars.EXECUTABLE_FILENAME || github.event.repository.name }}
jobs:
  build-nextjs:
    uses: ./.github/workflows/build-nextjs.yml
    with:
      workingDirectory: ui
      outputArtifactName: output-nextjs
  build-go:
    uses: ./.github/workflows/build-go.yml
    needs: build-nextjs
    with:
      inputArtifactName: output-nextjs
      inputArtifactPath: ui/out
      executableFilename: ${{ inputs.executableFilename }}
      outputArtifactName: output-go
  deploy-ssh:
    uses: ./.github/workflows/deploy-ssh.yml
    needs: build-go
    secrets: inherit
    with:
      inputArtifactName: output-go
      preDeployCommand: screen -S ${{ inputs.executableFilename }} -X quit; true
      postDeployCommand: chmod 700 ${{ inputs.executableFilename }}; source .env; screen -dmS ${{ inputs.executableFilename }} ./${{ inputs.executableFilename }}
