name: Build Go executable and deploy over SSH (preset 1)
on:
  workflow_call:
    inputs:
      executableFilename:
        required: false
        type: string
        default: ${{ vars.EXECUTABLE_FILENAME || github.event.repository.name }}
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-go:
    uses: ./.github/workflows/build-go.yml
    with:
      executableFilename: ${{ inputs.executableFilename }}
      outputArtifactName: output-go
  deploy-ssh:
    uses: ./.github/workflows/deploy-ssh.yml
    needs: build-go
    secrets: inherit
    with:
      inputArtifactName: output-go
      preDeployCommand: screen -S ${{ inputs.executableFilename }} -X quit; true
      postDeployCommand: chmod 700 ${{ inputs.executableFilename }}; source .env; screen -dmS ${{ inputs.executableFilename }} ./${{ inputs.executableFilename }}
