on:
  workflow_call:
    inputs:
      preservePreviousOutput:
        required: false
        type: boolean
        default: ${{ vars.PRESERVE_PREVIOUS_OUTPUT == 'true' }}
concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true
jobs:
  build-nextjs:
    uses: ./.github/workflows/build-nextjs.yml
    with:
      outputArtifactName: output-nextjs
  deploy-ssh:
    uses: ./.github/workflows/deploy-ssh.yml
    needs: build-nextjs
    secrets: inherit
    with:
      inputArtifactName: output-nextjs
      preDeployCommand: ${{ (inputs.preservePreviousOutput && 'mkdir -p old; mv * .* old') || 'rm -rf * .*' }}; true
