on:
  workflow_call:
    inputs:
      preBuildCommand:
        required: false
        type: string
        default: ${{ vars.PRE_BUILD_COMMAND }}
      executableFilename:
        required: false
        type: string
        default: ${{ vars.EXECUTABLE_FILENAME || github.event.repository.name }}
      screenName:
        required: false
        type: string
        default: ${{ vars.SCREEN_NAME || github.event.repository.name }}
concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true
jobs:
  build-go:
    uses: ./.github/workflows/build-go.yml
    with:
      preBuildCommand: ${{ inputs.preBuildCommand }}
      executableFilename: ${{ inputs.executableFilename }}
      outputArtifactName: output-go
  deploy-ssh:
    uses: ./.github/workflows/deploy-ssh.yml
    needs: build-go
    secrets: inherit
    with:
      inputArtifactName: output-go
      payloadPath: linux-amd64
      preDeployCommand: screen -S ${{ inputs.screenName }} -X quit; true
      postDeployCommand: chmod 700 ${{ inputs.executableFilename }}; source .env; screen -dmS ${{ inputs.screenName }} ./${{ inputs.executableFilename }}
