name: Build Go executable and deploy over SSH (preset 2)
on:
  workflow_call:
env:
  EXECUTABLE_FILENAME: ${{ vars.OUTPUT_FILENAME || github.event.repository.name }}
jobs:
  build-nextjs:
    uses: ./.github/workflows/build-nextjs.yml
    with:
      workingDirectory: ui
      outputArtifactName: output-nextjs
  build-go:
    uses: ./.github/workflows/build-go.yml
    needs: build-nextjs
    with:
      inputArtifactName: output-nextjs
      executableFilename: ${{ env.EXECUTABLE_FILENAME }}
      outputArtifactName: output-go
  deploy-ssh:
    uses: ./.github/workflows/deploy-ssh.yml
    needs: build-go
    secrets: inherit
    with:
      inputArtifactName: output-go
      preDeployCommand: screen -S ${{ env.EXECUTABLE_FILENAME }} -X quit; true
      postDeployCommand: chmod 700 ${{ env.EXECUTABLE_FILENAME }}; source .env; screen -dmS ${{ env.EXECUTABLE_FILENAME }} ./${{ env.EXECUTABLE_FILENAME }}
