on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-python:
    uses: ./.github/workflows/build-python.yml
    with:
      outputArtifactName: output-python
  release-github:
    uses: ./.github/workflows/release-github.yml
    needs: build-python
    with:
      inputArtifactName: output-python
      monoPack: true
      version: ${{ github.sha }}
