on:
  workflow_call:
    inputs:
      executableFilename:
        required: false
        type: string
        default: ${{ vars.EXECUTABLE_FILENAME || github.event.repository.name }}
      version:
        required: true
        type: string
concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true
jobs:
  build-go:
    uses: ./.github/workflows/build-go.yml
    with:
      executableFilename: ${{ inputs.executableFilename }}
      crossCompile: true
      outputArtifactName: output-go
  release-github:
    uses: ./.github/workflows/release-github.yml
    needs: build-go
    with:
      inputArtifactName: output-go
      version: ${{ inputs.version }}
