name: Build Go executable
on:
  workflow_call:
    inputs:
      inputArtifactName:
        required: false
        type: string
      inputArtifactPath:
        required: false
        type: string
      executableFilename:
        required: true
        type: string
      crossCompile:
        required: false
        type: boolean
      additionalOutputFiles:
        required: false
        type: string
      outputArtifactName:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Download artifact
        if: ${{ inputs.inputArtifactName != '' && inputs.inputArtifactPath != '' }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.inputArtifactName }}
          path: ${{ inputs.inputArtifactPath }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Build (Linux)
        run: GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -trimpath -o artifact/${{ inputs.executableFilename }}
      - name: Build (Windows)
        if: ${{ inputs.crossCompile }}
        run: GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -trimpath -o artifact/${{ inputs.executableFilename }}.exe
      - name: Bundle additional output files
        if: ${{ inputs.additionalOutputFiles != '' }}
        run: cp ${{ inputs.additionalOutputFiles }} artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.outputArtifactName }}
          path: artifact
