name: Build Go binary
on:
  workflow_call:
    inputs:
      outputFilename:
        required: true
        type: string
      additionalFiles:
        required: false
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Build
        run: go build -ldflags "-s -w" -trimpath -o artifact/${{ inputs.outputFilename }}
      - name: Copy additional files
        if: ${{ inputs.additionalFiles != '' }}
        run: cp ${{ inputs.additionalFiles }} artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: artifact
