on:
  workflow_call:
    inputs:
      preBuildCommand:
        required: false
        type: string
        default: ${{ vars.PRE_BUILD_COMMAND }}
      executableFilename:
        required: false
        type: string
        default: ${{ vars.EXECUTABLE_FILENAME || github.event.repository.name }}
      isGuiApp:
        required: false
        type: boolean
        default: ${{ vars.IS_GUI_APP == 'true' }}
      version:
        required: true
        type: string
concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true
jobs:
  build-go:
    uses: ./.github/workflows/build-go.yml
    with:
      preBuildCommand: ${{ inputs.preBuildCommand }}
      executableFilename: ${{ inputs.executableFilename }}
      buildWindows: true
      isGuiApp: ${{ inputs.isGuiApp }}
      outputArtifactName: output-go
  release-github:
    uses: ./.github/workflows/release-github.yml
    needs: build-go
    with:
      inputArtifactName: output-go
      version: ${{ inputs.version }}
