on:
  workflow_call:
    inputs:
      executableFilename:
        required: false
        type: string
        default: ${{ vars.EXECUTABLE_FILENAME || github.event.repository.name }}
concurrency:
  group: ${{ github.workflow }} ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-nextjs:
    uses: ./.github/workflows/build-nextjs.yml
    with:
      workingDirectory: ui
      outputArtifactName: output-nextjs
  build-go:
    uses: ./.github/workflows/build-go.yml
    needs: build-nextjs
    with:
      inputArtifactName: output-nextjs
      inputArtifactPath: ui/out
      executableFilename: ${{ inputs.executableFilename }}
      crossCompile: true
      outputArtifactName: output-go
  release-github:
    uses: ./.github/workflows/release-github.yml
    needs: build-go
    with:
      inputArtifactName: output-go
      version: ${{ github.sha }}
