name: Build and export Next.js static site
on:
  workflow_call:
    inputs:
      workingDirectory:
        required: false
        type: string
      outputArtifactName:
        required: true
        type: string
jobs:
  build-nextjs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workingDirectory }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: ${{ inputs.workingDirectory }}/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build and export
        run: npx --no next build && npx --no next export
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.outputArtifactName }}
          path: ${{ inputs.workingDirectory }}/out
