name: Build Go executable
on:
  workflow_call:
    inputs:
      inputArtifactName:
        required: false
        type: string
      inputArtifactPath:
        required: false
        type: string
      preBuildCommand:
        required: false
        type: string
      executableFilename:
        required: true
        type: string
      buildLinux:
        required: false
        type: boolean
        default: true
      buildWindows:
        required: false
        type: boolean
      isGuiApp:
        required: false
        type: boolean
      additionalOutputFiles:
        required: false
        type: string
      outputArtifactName:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Download artifact
        if: ${{ inputs.inputArtifactName != '' && inputs.inputArtifactPath != '' }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.inputArtifactName }}
          path: ${{ inputs.inputArtifactPath }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Run pre-build command
        if: ${{ inputs.preBuildCommand != '' }}
        run: ${{ inputs.preBuildCommand }}
      - name: Build (Linux)
        if: ${{ inputs.buildLinux }}
        run: GOARCH=amd64 GOOS=linux go build -ldflags "-s -w" -trimpath -o artifact/linux-amd64/${{ inputs.executableFilename }}
      - name: Bundle additional output files (Linux)
        if: ${{ inputs.buildLinux && inputs.additionalOutputFiles != '' }}
        run: cp ${{ inputs.additionalOutputFiles }} artifact/linux-amd64
      - name: Build (Windows)
        if: ${{ inputs.buildWindows }}
        run: GOARCH=amd64 GOOS=windows go build -ldflags "-s -w${{ (inputs.isGuiApp && ' -H windowsgui') || '' }}" -trimpath -o artifact/windows-amd64/${{ inputs.executableFilename }}.exe
      - name: Bundle additional output files (Windows)
        if: ${{ inputs.buildWindows && inputs.additionalOutputFiles != '' }}
        run: cp ${{ inputs.additionalOutputFiles }} artifact/windows-amd64
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.outputArtifactName }}
          path: artifact
