name: Release on GitHub
on:
  workflow_call:
    inputs:
      inputArtifactName:
        required: true
        type: string
      monoPack:
        required: false
        type: boolean
      version:
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Abort if ref isn't a tag and release already exists
        if: ${{ github.ref_type != 'tag' }}
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release view ${{ inputs.version }} |& grep "release not found"
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.inputArtifactName }}
          path: release
      - name: Prepare release files
        run: |
          if ${{ inputs.monoPack }}; then
            mv release ${{ github.event.repository.name }}
            mkdir release
            mv ${{ github.event.repository.name }} release
            cd release
            zip -rm ${{ github.event.repository.name }}-${{ inputs.version }}.zip ${{ github.event.repository.name }}
          else
            cd release
            for filename in *; do
              if [[ -d $filename ]]; then
                mv $filename ${{ github.event.repository.name }}
                zip -rm ${{ github.event.repository.name }}-${{ inputs.version }}-$filename.zip ${{ github.event.repository.name }}
              fi
            done
          fi
      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          tag_name: ${{ inputs.version }}
          generate_release_notes: true
          files: release/*
